"""Add collections

Revision ID: 619aea53c1a9
Revises: e5b363df94a0
Create Date: 2026-06-10 22:25:36.241974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '619aea53c1a9'
down_revision: Union[str, Sequence[str], None] = 'e5b363df94a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Add default collection for existing documents
    op.execute("INSERT INTO collections (id, name, description, settings) VALUES ('default-collection', 'Default Collection', 'Default collection for existing documents', '{}')")
    
    # Add column as nullable first
    op.add_column('documents', sa.Column('collection_id', sa.String(), nullable=True))
    
    # Update existing documents
    op.execute("UPDATE documents SET collection_id = 'default-collection' WHERE collection_id IS NULL")
    
    # Make column non-nullable
    op.alter_column('documents', 'collection_id', nullable=False)
    
    op.create_foreign_key('fk_document_collection_id', 'documents', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_document_collection_id', 'documents', type_='foreignkey')
    op.drop_column('documents', 'collection_id')
    op.drop_table('collections')
    # ### end Alembic commands ###
